settings:
  files:
    outputs:
      status: true
      path: ""
      name: .r.outputs.log
    logs:
      status: true
      path: ""
      name: .r.logs.log
    errors:
      status: true
      path: ""
      name: .r.errors.log
  legacy:
    force: true
    interval: 100ms
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
- name: gin
  path: C:\Users\Administrator\go\src\gin
  commands:
    clean:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    scripts:
    - type: before
      command: taskkill /im [executable].exe /F
